spring.datasource.url=jdbc:postgresql://localhost:5432/nexusHR
spring.datasource.username=postgres
spring.datasource.password=psql12345612
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081