import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as htmlToImage from 'html-to-image';

export interface ReportKPI {
  label: string;
  value: string | number;
}

export interface ReportData {
  kpis?: ReportKPI[];
  tableHeaders: string[];
  tableRows: any[];
}

export async function exportDashboardPdf(element: HTMLElement, filename: string = 'dashboard-report') {
  // Legacy method fallback if ever needed
  const imgData = await htmlToImage.toPng(element, { backgroundColor: '#ffffff', pixelRatio: 2 });
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Create an image element to get dimensions
  const img = new Image();
  img.src = imgData;
  await new Promise((resolve) => { img.onload = resolve; });

  const imgWidth = pageWidth - 20;
  const imgHeight = (img.height * imgWidth) / img.width;
  let heightLeft = imgHeight;
  let position = 10;
  pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
  heightLeft -= pageHeight - 20;
  while (heightLeft > 0) {
    position = heightLeft - imgHeight + 10;
    pdf.addPage();
    pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - 20;
  }
  pdf.save(`${filename}-${new Date().toISOString().split('T')[0]}.pdf`);
}

export async function generateEnterprisePdf(
  reportTitle: string,
  reportData: ReportData,
  chartElement: HTMLElement | null,
  filename: string
) {
  const isLandscape = reportData.tableHeaders.length > 6;
  const pdf = new jsPDF(isLandscape ? 'l' : 'p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 15;
  let currentY = margin;

  // 1. Company Header
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(16, 185, 129); // Emerald 500 for NexusHR brand
  pdf.text('NexusHR', margin, currentY + 8);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text('Enterprise Report Generation', margin, currentY + 14);

  // Right side header info
  pdf.setFontSize(10);
  pdf.setTextColor(50, 50, 50);
  const now = new Date();
  const dateStr = now.toLocaleDateString() + ' ' + now.toLocaleTimeString();
  pdf.text(`Generated: ${dateStr}`, pageWidth - margin, currentY + 8, { align: 'right' });
  pdf.text(`Generated by: NexusHR System`, pageWidth - margin, currentY + 14, { align: 'right' });

  currentY += 22;
  
  // Line separator
  pdf.setDrawColor(220, 220, 220);
  pdf.line(margin, currentY, pageWidth - margin, currentY);
  currentY += 12;

  // Report Title
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text(reportTitle, margin, currentY + 6);
  currentY += 16;

  // 2. Summary Section
  if (reportData.kpis && reportData.kpis.length > 0) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(50, 50, 50);
    pdf.text('Executive Summary', margin, currentY);
    currentY += 6;

    const itemsPerRow = isLandscape ? 5 : 4;
    const gap = 5;
    const boxWidth = (pageWidth - 2 * margin - (gap * (itemsPerRow - 1))) / itemsPerRow;
    let startX = margin;

    pdf.setFontSize(9);
    
    reportData.kpis.forEach((kpi, idx) => {
      if (idx > 0 && idx % itemsPerRow === 0) {
        currentY += 18; // New row
        startX = margin;
      }
      
      pdf.setDrawColor(230, 230, 230);
      pdf.setFillColor(248, 250, 252);
      pdf.roundedRect(startX, currentY, boxWidth, 14, 1.5, 1.5, 'FD');
      
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(100, 100, 100);
      pdf.text(kpi.label, startX + 3, currentY + 5);
      
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(30, 30, 30);
      pdf.text(String(kpi.value), startX + 3, currentY + 11);
      
      startX += boxWidth + gap;
    });
    
    currentY += 22;
  }

  // 3. Charts
  if (chartElement) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(50, 50, 50);
    pdf.text('Analytics', margin, currentY);
    currentY += 4;

    const imgData = await htmlToImage.toPng(chartElement, {
      backgroundColor: '#ffffff',
      pixelRatio: 2,
      skipFonts: true,
    });
    
    // Get image dimensions
    const img = new Image();
    img.src = imgData;
    await new Promise((resolve) => { img.onload = resolve; });

    // Ensure chart fits nicely. We'll constrain it to 60% of page height max.
    const maxImgHeight = pdf.internal.pageSize.getHeight() * 0.4;
    let imgWidth = pageWidth - 2 * margin;
    let imgHeight = (img.height * imgWidth) / img.width;
    
    if (imgHeight > maxImgHeight) {
      imgHeight = maxImgHeight;
      imgWidth = (img.width * imgHeight) / img.height;
    }
    
    // Center it
    const xOffset = margin + ((pageWidth - 2 * margin - imgWidth) / 2);
    
    // Check if we need a new page
    if (currentY + imgHeight > pdf.internal.pageSize.getHeight() - 20) {
      pdf.addPage();
      currentY = margin;
    }
    
    pdf.addImage(imgData, 'PNG', xOffset, currentY, imgWidth, imgHeight);
    currentY += imgHeight + 12;
  }

  // 4. Data Table
  if (reportData.tableHeaders && reportData.tableRows) {
    let rows: any[] = [];
    let customStyles: any = {};
    
    if (reportData.tableRows.length > 0 && ('cells' in reportData.tableRows[0])) {
      reportData.tableRows.forEach((row, rowIndex) => {
        rows.push(row.cells);
        customStyles[rows.length - 1] = { fontStyle: 'bold', fillColor: [241, 245, 249] };
        
        if (row.subRows && row.subRows.length > 0) {
          row.subRows.forEach((sub: any) => {
             const subRow = [...sub];
             // Add a visual indent to the first column
             subRow[0] = '    ' + subRow[0];
             rows.push(subRow);
          });
        }
      });
    } else {
      // Fallback for flat string array rows
      rows = reportData.tableRows;
    }

    (pdf as any).autoTable({
      startY: currentY,
      head: [reportData.tableHeaders],
      body: rows,
      theme: 'grid',
      headStyles: {
        fillColor: [16, 185, 129], // Emerald 500
        textColor: 255,
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
      },
      alternateRowStyles: {
        fillColor: [252, 253, 255],
      },
      // Apply custom bold styles to group header rows
      didParseCell: function (data) {
        if (data.section === 'body' && customStyles[data.row.index]) {
          data.cell.styles.fontStyle = customStyles[data.row.index].fontStyle;
          data.cell.styles.fillColor = customStyles[data.row.index].fillColor;
        }
      },
      margin: { top: margin, left: margin, right: margin, bottom: 20 },
      didDrawPage: function (data) {
        // Footer on every page
        const str = 'Page ' + pdf.internal.getNumberOfPages();
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(150, 150, 150);
        
        const pageHeight = pdf.internal.pageSize.getHeight();
        pdf.text(str, pageWidth - margin, pageHeight - 10, { align: 'right' });
        pdf.text('This is a computer-generated report.', margin, pageHeight - 10);
      },
    });
  }

  // Check if we need to add a footer to the first page if there was no table
  if (!reportData.tableHeaders || reportData.tableHeaders.length === 0) {
    const str = 'Page ' + pdf.internal.getNumberOfPages();
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(150, 150, 150);
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.text(str, pageWidth - margin, pageHeight - 10, { align: 'right' });
    pdf.text('This is a computer-generated report.', margin, pageHeight - 10);
  }

  const safeTitle = reportTitle.replace(/[^a-z0-9]/gi, '_');
  pdf.save(`${filename}.pdf`);
}
